### ISSUE TITLE
pkg: pyspark

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#47]
in nix-shell:

pyspark
```
  File "/nix/store/xrfdr77hry03gshj0jkqcbx5r0l9wv5g-python3.7-pyspark-2.4.6/bin/find_spark_home.py", line 2
    export PATH='/nix/store/9hdzs3g6rb76grwzlsbxyxwxg2n0fl4a-python3-3.7.8/bin:/nix/store/xrfdr77hry03gshj0jkqcbx5r0l9wv5g-python3.7-pyspark-2.4.6/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
/nix/store/xrfdr77hry03gshj0jkqcbx5r0l9wv5g-python3.7-pyspark-2.4.6/bin/pyspark: line 24: /bin/load-spark-env.sh: No such file or directory
/nix/store/xrfdr77hry03gshj0jkqcbx5r0l9wv5g-python3.7-pyspark-2.4.6/bin/pyspark: line 77: /bin/spark-submit: No such file or directory
```

**Comment by cript0nauta** [comment]
This is a nixpkgs issue. See https://github.com/NixOS/nixpkgs/issues/64358 and https://github.com/NixOS/nixpkgs/pull/64740.

The nixpkgs pull request fixing this bug isn't merged and seems to be staled. Because nixpkgs PRs can take a while to be merged, a workaround I would suggest is to keep your own nixpkgs branch where you can apply some fixes (for this case, it would be https://github.com/NixOS/nixpkgs/pull/64740/commits/e4942731b45cb0e7d7ba331e61025d88bcedbb07). Then, you can use pynixify's `--nixpkgs` option in order to use your own branch. As an example of this approach, you can see the [commits of the branch I maintain for my project](https://github.com/infobyte/nixpkgs/commits/faraday-fork-20.03).

Hope this resulted helpful! I'll close the issue since its not directly related to pynixify.
